apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: gcr.io/chaos-camp/app
    context: app
    jibGradle: {}
  - image: gcr.io/chaos-camp/hasher
    context: hasher
    jibGradle: {}
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - app/kubernetes/*
    - hasher/kubernetes/*