apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoscamp-app
spec:
  selector:
    matchLabels:
      app: chaoscamp-app
  replicas: 3
  template:
    metadata:
      labels:
        app: chaoscamp-app
    spec:
      containers:
        - name: chaoscamp-app
          image: gcr.io/chaos-camp/app:latest
          ports:
            - containerPort: 8081
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          resources:
            limits:
              memory: "256M"
              cpu: "0.1"