apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoscamp-toxiproxy
spec:
  selector:
    matchLabels:
      app: chaoscamp-toxiproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: chaoscamp-toxiproxy
    spec:
      containers:
      - name: toxiproxy
        image: gcr.io/chaos-camp/toxiproxy
        ports:
          - containerPort: 8474
          - containerPort: 8082