apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoscamp-hasher
spec:
  selector:
    matchLabels:
      app: chaoscamp-hasher
  replicas: 3
  template:
    metadata:
      labels:
        app: chaoscamp-hasher
    spec:
      containers:
      - name: chaoscamp-hasher
        image: gcr.io/chaos-camp/hasher:latest
        ports:
        - containerPort: 8082
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: chaos-monkey
          - name: JAVA_TOOL_OPTIONS
            value: "-Dcom.sun.management.jmxremote
              -Dcom.sun.management.jmxremote.authenticate=false
              -Dcom.sun.management.jmxremote.ssl=false
              -Dcom.sun.management.jmxremote.local.only=false
              -Dcom.sun.management.jmxremote.port=1099
              -Dcom.sun.management.jmxremote.rmi.port=1099
              -Djava.rmi.server.hostname=127.0.0.1"
        resources:
          limits:
            memory: "256M"
            cpu: "0.25"