apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoscamp-hasher
spec:
  selector:
    matchLabels:
      app: chaoscamp-hasher
  replicas: 3
  template:
    metadata:
      labels:
        app: chaoscamp-hasher
    spec:
      containers:
      - name: chaoscamp-hasher
        image: gcr.io/chaos-camp/hasher:latest
        ports:
        - containerPort: 8082
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: chaos-monkey
